import os

TWILIO_ACCOUNT_SID='XXXXXXXXXXXXXXX'
TWILIO_AUTH_TOKEN='XXXXXXXXXXXXXXXX'
AIRTABLE_API_KEY=os.environ.get('AIRTABLE_API_KEY', 'XXXXXXXXXXXXXXXXX')
AIRTABLE_BASE_KEY=os.environ.get('AIRTABLE_BASE_KEY', 'XXXXXXXXXXXXXXXXX')
